// User-visible strings for the widget. `es` is the source of truth (taken
// from the shipped application); `en` is the translation. Every string the
// widget renders comes from a pack — templates use {placeholders}.

import type { Labels } from './types'

/** Replaces `{key}` placeholders in a label template. Unknown keys are left as-is. */
export function fill(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (match, key: string) =>
    Object.prototype.hasOwnProperty.call(vars, key) ? String(vars[key]) : match,
  )
}

const es: Labels = {
  // Title bar
  appTitle: 'Event Timeline',
  menu: 'Menú',
  winMinimize: 'Minimizar',
  winMaximize: 'Maximizar',
  winClose: 'Cerrar',
  openEvtx: 'Abrir EVTX',
  newLocalIncident: 'Nuevo incidente local',
  saveIncident: 'Guardar incidente',
  closeIncident: 'Cerrar incidente',
  // Time corridor strip
  timeCorridor: 'Pasillo de tiempo',
  corridorRange: '({from} - {to})',
  start: 'Inicio',
  end: 'Fin',
  apply: 'Aplicar',
  pickStart: 'Elegir fecha y hora de inicio',
  pickEnd: 'Elegir fecha y hora de fin',
  // Context panel
  context: 'CONTEXTO',
  incident: 'INCIDENTE',
  name: 'Nombre',
  computer: 'Equipo',
  description: 'Descripción',
  incidentNote: 'Nota del incidente',
  localTime: 'Hora local · {tz}',
  layers: 'Capas',
  incidentMark: 'Marca de incidente',
  bookmarks: 'Marcadores',
  levelHeader: 'NIVEL',
  levelCritical: 'Crítico',
  levelError: 'Error',
  levelWarning: 'Advertencia',
  levelInformation: 'Información',
  levelVerbose: 'Detallado',
  play: 'Reproducir',
  pause: 'Pausar',
  collapseContext: 'Contraer panel de contexto',
  expandContext: 'Expandir panel de contexto',
  collapseDetails: 'Contraer panel de detalles',
  expandDetails: 'Expandir panel de detalles',
  // Center header + search
  unifiedTimeline: 'LÍNEA DE TIEMPO UNIFICADA',
  eventCounter: '{total} eventos, mostrando {shown}',
  span15m: '15m',
  span1h: '1h',
  span6h: '6h',
  span24h: '24h',
  fit: 'Ajustar',
  zoomOut: 'Alejar',
  zoomIn: 'Acercar',
  filters: 'Filtros',
  search: 'Búsqueda',
  searchPlaceholder: 'Buscar proveedor, mensaje, Id. de evento o campos visibles',
  loadedCorridorOnly: 'Solo pasillo cargado',
  resetFilters: 'Restablecer',
  // Ruler + plot footer
  timeRuler: 'REGLA DE TIEMPO',
  visibleWindowLabel: 'Ventana visible:',
  windowRange: '{from} - {to} ({duration})',
  visibleClusters: '{visible} visibles · {clusters} agrupados',
  localQueryDone: 'Consulta local completada.',
  utcRange: '[{from}, {to}] (UTC inclusivo)',
  // Details panel
  eventDetails: 'DETALLES DEL EVENTO',
  tabDetails: 'Detalles',
  tabXml: 'XML',
  provider: 'Proveedor',
  eventIdLabel: 'Id. de evento',
  levelLabel: 'Nivel',
  dateLabel: 'Fecha',
  timeLabel: 'Hora',
  channel: 'Canal',
  category: 'Categoría',
  origin: 'Origen',
  processId: 'Id. de proceso',
  threadId: 'Id. de subproc',
  lane: 'Carril',
  structuredData: 'Datos estructurados',
  markerNote: 'Nota del marcador',
  copyStructured: 'Copiar datos estructurados',
  copied: 'Copiado',
  noSelection: 'Selecciona un evento para ver sus detalles.',
  // Canvas + markers
  canvasAria: 'Línea de tiempo de eventos interactiva',
  toggleLane: 'Mostrar u ocultar {lane}',
  clusterLabel: '{count} eventos agrupados',
  markerLabel: 'Evento a las {time}',
  markerLabelFull: 'Evento a las {time} — {provider}',
  dash: '—',
}

const en: Labels = {
  // Title bar
  appTitle: 'Event Timeline',
  menu: 'Menu',
  winMinimize: 'Minimize',
  winMaximize: 'Maximize',
  winClose: 'Close',
  openEvtx: 'Open EVTX',
  newLocalIncident: 'New local incident',
  saveIncident: 'Save incident',
  closeIncident: 'Close incident',
  // Time corridor strip
  timeCorridor: 'Time corridor',
  corridorRange: '({from} - {to})',
  start: 'Start',
  end: 'End',
  apply: 'Apply',
  pickStart: 'Pick start date and time',
  pickEnd: 'Pick end date and time',
  // Context panel
  context: 'CONTEXT',
  incident: 'INCIDENT',
  name: 'Name',
  computer: 'Computer',
  description: 'Description',
  incidentNote: 'Incident note',
  localTime: 'Local time · {tz}',
  layers: 'Layers',
  incidentMark: 'Incident mark',
  bookmarks: 'Bookmarks',
  levelHeader: 'LEVEL',
  levelCritical: 'Critical',
  levelError: 'Error',
  levelWarning: 'Warning',
  levelInformation: 'Information',
  levelVerbose: 'Verbose',
  play: 'Play',
  pause: 'Pause',
  collapseContext: 'Collapse context panel',
  expandContext: 'Expand context panel',
  collapseDetails: 'Collapse details panel',
  expandDetails: 'Expand details panel',
  // Center header + search
  unifiedTimeline: 'UNIFIED TIMELINE',
  eventCounter: '{total} events, showing {shown}',
  span15m: '15m',
  span1h: '1h',
  span6h: '6h',
  span24h: '24h',
  fit: 'Fit',
  zoomOut: 'Zoom out',
  zoomIn: 'Zoom in',
  filters: 'Filters',
  search: 'Search',
  searchPlaceholder: 'Search provider, message, event ID or visible fields',
  loadedCorridorOnly: 'Loaded corridor only',
  resetFilters: 'Reset',
  // Ruler + plot footer
  timeRuler: 'TIME RULER',
  visibleWindowLabel: 'Visible Window:',
  windowRange: '{from} - {to} ({duration})',
  visibleClusters: '{visible} visible · {clusters} clusters',
  localQueryDone: 'Local query completed.',
  utcRange: '[{from}, {to}] (inclusive UTC)',
  // Details panel
  eventDetails: 'EVENT DETAILS',
  tabDetails: 'Details',
  tabXml: 'XML',
  provider: 'Provider',
  eventIdLabel: 'Event ID',
  levelLabel: 'Level',
  dateLabel: 'Date',
  timeLabel: 'Time',
  channel: 'Channel',
  category: 'Category',
  origin: 'Source',
  processId: 'Process ID',
  threadId: 'Thread ID',
  lane: 'Lane',
  structuredData: 'Structured data',
  markerNote: 'Marker note',
  copyStructured: 'Copy structured data',
  copied: 'Copied',
  noSelection: 'Select an event to see its details.',
  // Canvas + markers
  canvasAria: 'Interactive event timeline',
  toggleLane: 'Show or hide {lane}',
  clusterLabel: '{count} grouped events',
  markerLabel: 'Event at {time}',
  markerLabelFull: 'Event at {time} — {provider}',
  dash: '—',
}

export const labels: { es: Labels; en: Labels } = { es, en }
